import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';
import crypto from 'crypto';
import { parseRouteFile, scanDir } from './router.js';

export async function generateSDK(routesDir = path.join(process.cwd(), 'routes'), outputPath = path.join(process.cwd(), 'bro-sdk.js')) {
    if (!fs.existsSync(routesDir)) {
    throw new Error(`Routes directory not found at ${routesDir}`);
  }

  const files = scanDir(routesDir);
  const endpoints = [];

  let routeCounter = 0;
  for (const file of files) {
    const routeInfo = parseRouteFile(file, routesDir);
    if (routeInfo) {
      const moduleUrl = pathToFileURL(file).href + '?update=' + crypto.randomUUID();
      const mod = await import(moduleUrl);
      const config = mod.default;

      if (!config.params && !config.query && !config.body) {
         console.warn(`\x1b[33m[bro.js] ⚠️ SDK Warning: Route ${routeInfo.method.toUpperCase()} ${routeInfo.routePath} has no schema validation (params/query/body). It will be untyped.\x1b[0m`);
      }

      endpoints.push({
        ...routeInfo,
        file,
        moduleName: `Route${routeCounter++}`
      });
    }
  }

  const jsCode = `// Auto-generated by bro.js
const CONFIG = {
  baseURL: 'http://localhost:5000',
  tokenKey: 'bro_token',
  locale: undefined
};

async function request(method, path, data) {
  const headers = {};

  if (CONFIG.locale) {
    headers['Accept-Language'] = CONFIG.locale;
  }
  
  if (typeof localStorage !== 'undefined') {
    const token = localStorage.getItem(CONFIG.tokenKey);
    if (token) {
      headers['Authorization'] = \`Bearer \${token}\`;
    }
  }

  const options = {
    method: method.toUpperCase(),
    headers
  };

  if (data && ['POST', 'PUT', 'PATCH'].includes(method.toUpperCase())) {
    headers['Content-Type'] = 'application/json';
    options.body = JSON.stringify(data);
  } else if (data && ['GET', 'DELETE'].includes(method.toUpperCase())) {
    const params = new URLSearchParams(data);
    const qs = params.toString();
    if (qs) {
      path += '?' + qs;
    }
  }

  const url = CONFIG.baseURL + path;
  const response = await fetch(url, options);
  
  if (!response.ok) {
    let errMessage = response.statusText;
    try {
      const errData = await response.json();
      errMessage = errData.error || errData.message || errMessage;
    } catch (e) {}
    throw new Error(\`HTTP \${response.status}: \${errMessage}\`);
  }

  return response.json();
}

export const api = {
${generateApiObject(endpoints, false)}
};

export function setBaseURL(url) {
  CONFIG.baseURL = url;
}

export function setTokenKey(key) {
  CONFIG.tokenKey = key;
}

export function setLocale(locale) {
  CONFIG.locale = locale;
}
`;

  fs.writeFileSync(path.join(process.cwd(), 'bro-sdk.js'), jsCode, 'utf-8');

  let typeImports = `// Auto-generated by bro.js
import type { z } from 'zod';
`;

  for (const ep of endpoints) {
    let relativePath = './' + path.relative(process.cwd(), ep.file).replace(/\\/g, '/');
    if (relativePath.endsWith('.js')) {
       // TS allows importing .js directly if allowJs is true, or you can omit the extension
    }
    typeImports += `import type ${ep.moduleName} from '${relativePath}';\n`;
  }

  const typeDefs = `
type Infer<T> = T extends import('zod').ZodType<infer O, any, infer I> ? I : any;
type RouteData<C> = (C extends { body: any } ? Infer<C['body']> : {}) & (C extends { query: any } ? Infer<C['query']> : {}) & (C extends { params: any } ? Infer<C['params']> : {});
type SafeData<C> = keyof RouteData<C> extends never ? any : RouteData<C>;

export declare const api: {
${generateApiObject(endpoints, true)}
};

export declare function setBaseURL(url: string): void;
export declare function setTokenKey(key: string): void;
export declare function setLocale(locale: string): void;
`;

  fs.writeFileSync(path.join(process.cwd(), 'bro-sdk.d.ts'), typeImports + typeDefs, 'utf-8');
}

function generateApiObject(endpoints, isTypes) {
  const tree = Object.create(null);
  
  for (const ep of endpoints) {
    const { routePath, method, moduleName } = ep;
    const parts = routePath.split('/').filter(Boolean);
    
    let current = tree;
    let pathAcc = '';
    
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isParam = part.startsWith(':');
      const name = isParam ? part.slice(1) : part;
      pathAcc += '/' + part;
      
      if (!current[name]) {
        current[name] = Object.assign(Object.create(null), { _isParam: isParam, _methods: Object.create(null), _children: Object.create(null), _path: pathAcc });
      } else {
        if (current[name]._isParam !== isParam) {
          throw new Error(`SDK Collision: Route segment "${name}" conflicts between static and dynamic parameters at path "${pathAcc}"`);
        }
      }
      
      if (i === parts.length - 1) {
        current[name]._methods[method.toLowerCase()] = { path: pathAcc, moduleName };
      }
      
      current = current[name]._children;
    }
    
    if (parts.length === 0) {
      if (!tree['root']) tree['root'] = Object.assign(Object.create(null), { _isParam: false, _methods: Object.create(null), _children: Object.create(null), _path: '/' });
      tree['root']._methods[method.toLowerCase()] = { path: '/', moduleName };
    }
  }

  function renderTree(node, indent = '  ') {
    let result = '';
    
    const isValidIdentifier = (key) => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
    
    for (const [key, val] of Object.entries(node)) {
      const formattedKey = isValidIdentifier(key) ? key : `"${key}"`;
      
      if (val._isParam) {
        if (isTypes) {
           result += `${indent}${formattedKey}: (${key}: string | number) => {\n`;
        } else {
           result += `${indent}${formattedKey}: (${key}) => ({\n`;
        }
        
        for (const [m, info] of Object.entries(val._methods)) {
          if (isTypes) {
             result += `${indent}  ${m}: (data?: SafeData<typeof ${info.moduleName}.default>) => Promise<any>;\n`;
          } else {
             const templatedPath = info.path.replace(/:([a-zA-Z0-9_$]+)/g, '\${encodeURIComponent($1)}');
             result += `${indent}  ${m}: (data) => request('${m}', \`${templatedPath}\`, data),\n`;
          }
        }
        
        const childrenStr = renderTree(val._children, indent + '  ');
        if (childrenStr) {
          result += childrenStr;
        }
        
        if (isTypes) {
           result += `${indent}};\n`;
        } else {
           result += `${indent}}),\n`;
        }
      } else {
        result += `${indent}${formattedKey}: {\n`;
        for (const [m, info] of Object.entries(val._methods)) {
           if (isTypes) {
              result += `${indent}  ${m}: (data?: SafeData<typeof ${info.moduleName}.default>) => Promise<any>;\n`;
           } else {
              result += `${indent}  ${m}: (data) => request('${m}', '${info.path}', data),\n`;
           }
        }
        
        const childrenStr = renderTree(val._children, indent + '  ');
        if (childrenStr) {
          result += childrenStr;
        }
        
        result += `${indent}},
`;
      }
    }
    return result;
  }

  return renderTree(tree);
}
