import fs from 'fs';
import path from 'path';
import { parseRouteFile, scanDir } from './router.js';

export async function generateSDK() {
  const routesDir = path.join(process.cwd(), 'routes');
  if (!fs.existsSync(routesDir)) {
    throw new Error(`Routes directory not found at ${routesDir}`);
  }

  const files = scanDir(routesDir);
  const endpoints = [];

  for (const file of files) {
    const routeInfo = parseRouteFile(file, routesDir);
    if (routeInfo) {
      endpoints.push(routeInfo);
    }
  }

  const code = `// Auto-generated by bro.js
const CONFIG = {
  baseURL: 'http://localhost:5000',
  tokenKey: 'bro_token'
};

async function request(method, path, data) {
  const headers = {};
  
  if (typeof localStorage !== 'undefined') {
    const token = localStorage.getItem(CONFIG.tokenKey);
    if (token) {
      headers['Authorization'] = \`Bearer \${token}\`;
    }
  }

  const options = {
    method: method.toUpperCase(),
    headers
  };

  if (data && ['POST', 'PUT', 'PATCH'].includes(method.toUpperCase())) {
    headers['Content-Type'] = 'application/json';
    options.body = JSON.stringify(data);
  } else if (data && ['GET', 'DELETE'].includes(method.toUpperCase())) {
    const params = new URLSearchParams(data);
    const qs = params.toString();
    if (qs) {
      path += '?' + qs;
    }
  }

  const url = CONFIG.baseURL + path;
  const response = await fetch(url, options);
  
  if (!response.ok) {
    let errMessage = response.statusText;
    try {
      const errData = await response.json();
      errMessage = errData.error || errData.message || errMessage;
    } catch (e) {}
    throw new Error(\`HTTP \${response.status}: \${errMessage}\`);
  }

  return response.json();
}

export const api = {
${generateApiObject(endpoints)}
};

export function setBaseURL(url) {
  CONFIG.baseURL = url;
}

export function setTokenKey(key) {
  CONFIG.tokenKey = key;
}
`;

  fs.writeFileSync(path.join(process.cwd(), 'bro-sdk.js'), code, 'utf-8');
}

function generateApiObject(endpoints) {
  const tree = {};
  
  for (const { routePath, method } of endpoints) {
    const parts = routePath.split('/').filter(Boolean);
    
    let current = tree;
    let pathAcc = '';
    
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isParam = part.startsWith(':');
      const name = isParam ? part.slice(1) : part;
      pathAcc += '/' + part;
      
      if (!current[name]) {
        current[name] = { _isParam: isParam, _methods: {}, _children: {}, _path: pathAcc };
      }
      
      if (i === parts.length - 1) {
        current[name]._methods[method.toLowerCase()] = pathAcc;
      }
      
      current = current[name]._children;
    }
    
    if (parts.length === 0) {
      if (!tree['root']) tree['root'] = { _isParam: false, _methods: {}, _children: {}, _path: '/' };
      tree['root']._methods[method.toLowerCase()] = '/';
    }
  }

  function renderTree(node, indent = '  ') {
    let result = '';
    
    for (const [key, val] of Object.entries(node)) {
      if (val._isParam) {
        result += `${indent}"${key}": (${key}) => ({\n`;
        
        for (const [m, p] of Object.entries(val._methods)) {
          const templatedPath = p.replace(/:([a-zA-Z0-9_]+)/g, '${encodeURIComponent($1)}');
          result += `${indent}  ${m}: (data) => request('${m}', \`${templatedPath}\`, data),\n`;
        }
        
        const childrenStr = renderTree(val._children, indent + '  ');
        if (childrenStr) {
          result += childrenStr;
        }
        
        result += `${indent}}),\n`;
      } else {
        result += `${indent}"${key}": {\n`;
        for (const [m, p] of Object.entries(val._methods)) {
           result += `${indent}  ${m}: (data) => request('${m}', '${p}', data),\n`;
        }
        
        const childrenStr = renderTree(val._children, indent + '  ');
        if (childrenStr) {
          result += childrenStr;
        }
        
        result += `${indent}},\n`;
      }
    }
    return result;
  }

  return renderTree(tree);
}
